### ISSUE TITLE
Handle MapSets like lists

### ISSUE THREAD

**Issue by tomciopp** [adobe/elixir-styler#113]
## Versions

* Elixir: use `elixir --version`: 1.16.0
* Styler: use `mix deps | grep locked | grep styler`: locked at 0.11.1 (styler) 8d995b3e

## Example Input

```elixir
@crud [
  none: 0,
  read: 1,
  write: 2,
  read_write: 3,
  delete: 4,
  read_delete: 5,
  write_delete: 6,
  all: 7
]

@read MapSet.new([
  :read,
  :read_write,
  :read_delete,
  :all,
  1,
  3,
  5,
  7
])
```

## Stacktrace / Current Behaviour

```elixir
@crud [
  none: 0,
  read: 1,
  write: 2,
  read_write: 3,
  delete: 4,
  read_delete: 5,
  write_delete: 6,
  all: 7
]

@read MapSet.new([
        :read,
        :read_write,
        :read_delete,
        :all,
        1,
        3,
        5,
        7
      ])
```

The MapSet format should not change, since it is functionally equivalent to the list.

**Comment by novaugust** [comment]
hey @tomciopp, that behaviour comes from elixir's Formatter, not styler =) cheers
