### ISSUE TITLE
Format causes breaking change for "<>"

### ISSUE THREAD

**Issue by wkirschbaum** [adobe/elixir-styler#114]
## Versions

* Elixir: Elixir 1.16.0 (compiled with Erlang/OTP 26)
* Styler: locked at 0.11.1 (styler) 8d995b3e

## Example Input

```elixir
"foo" <>
      ( for value <- 1..100 do
          "bar"
      end
      |> Enum.join(", "))
```

formats to invalid elixir: 

```elixir
    <>(
      "foo",
      for_result =
        for value <- 1..100 do
          "bar"
        end,
      Enum.join(for_result, ", ")
    )
 ```

`    error: syntax error before: '<>' `

**Comment by novaugust** [comment]
Thanks much for the repot + minimal repro example =) Will release 0.11.2 with a fix later today

**Comment by novaugust** [comment]
0.11.2 is released on hex with the fix :) cheers
