### ISSUE TITLE
Unexpectede behaviour for case + cond expressions (breaking dbg)

### ISSUE THREAD

**Issue by YannickFricke** [adobe/elixir-styler#117]
## Versions

* Elixir:
```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)
```

* Styler:
```
locked at 0.11.3 (styler) a0c6d4fb
```

## Example Input

```elixir
case true do
	true ->
		nil
	false ->
		nil
end
|> dbg()
```

## Stacktrace / Current Behaviour

The case expressions is extracted to its own variable and thus `dbg` does not work properly.

```elixir
case_result =
	case true do
		true ->
			nil
		false ->
			nil
	end

dbg(case_result)
```

Now you cannot see which arm of the case expression matched and only see the final result (which doesn't really help while debugging)

The same also applies to the "cond" expression:

```elixir
cond do
  123 ->
    456

  456 ->
    789

  true ->
    789
end
|> dbg()

# leads to

cond_result =
  cond do
    123 ->
      456

    456 ->
      789

    true ->
      789
  end

dbg(cond_result)
```

**Comment by novaugust** [comment]
hey @yannickfricke, thanks for the great writeup. sorry to say this behaviour is expected. styler's seeing a singular pipe - and a pipe starting with a case statement - and rewriting both of those style violations. i'd actually expect it to also rewrite that case statement to an if statement!
you can still use dbg in this situation by wrapping your case statement in it rather than piping, but yeah, styler's going to make you sad about the piping situation. apologies!

**Comment by YannickFricke** [comment]
@novaugust 
Heya thx for the fast reply!

That doesnt really work out when you use multiple pipes.

Example:
```elixir
defmodule Test do
  def test do
    dbg(
      case 123 do
        123 ->
          true

        456 ->
          true
          _(false)
      end
    )
    |> IO.inspect()
  end
end
```

Styler still rewrites it as the following:
```elixir
defmodule Test do
  def test do
    case_result =
      case 123 do
        123 ->
          true

        456 ->
          true
          _(false)
      end

    case_result
    |> dbg()
    |> IO.inspect()
  end
end
```

So this is really expected behavior even when its breaking the usefulness of "dbg"?

**Comment by YannickFricke** [comment]
And this is giving me the following compile error

```elixir
defmodule Test do
  def test do
    123
    |> IO.inspect()
    |> dbg(
      case do
        123 ->
          true

        234 ->
          true

        _ ->
          false
      end
    )
    |> IO.inspect()
  end
end
```

```
Compiling 1 file (.ex)
    error: the function "case" cannot handle clauses with the -> operator because it is not a macro. Please make sure you are invoking the proper name and that it is a macro
    │
  6 │       case do
    │       ^
    │
    └─ lib/test.ex:6:7: Test.test/0


== Compilation error in file lib/test.ex ==
** (CompileError) lib/test.ex: cannot compile module Test (errors have been logged)
    (elixir 1.16.0) expanding macro: Kernel.dbg/2
    lib/test.ex:5: Test.test/0
:error
```

**Comment by YannickFricke** [comment]
Maybe you're right:

```elixir
defmodule Test do
  def test do
    dbg(
      123
      |> IO.inspect()
      |> case do
        123 ->
          true

        234 ->
          true

        _ ->
          false
      end
      |> IO.inspect()
    )
  end
end
```

Prints out the following:

![grafik](https://github.com/adobe/elixir-styler/assets/591450/ae1c48ab-5f4c-4450-8f2c-b2be77341fa9)

**Comment by YannickFricke** [comment]
> Maybe you're right:
> 
> ```elixir
> defmodule Test do
>   def test do
>     dbg(
>       123
>       |> IO.inspect()
>       |> case do
>         123 ->
>           true
> 
>         234 ->
>           true
> 
>         _ ->
>           false
>       end
>       |> IO.inspect()
>     )
>   end
> end
> ```
> 
> Prints out the following:
> 
> ![grafik](https://private-user-images.githubusercontent.com/591450/296388097-ae1c48ab-5f4c-4450-8f2c-b2be77341fa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMDA5MTUsIm5iZiI6MTcwNTEwMDYxNSwicGF0aCI6Ii81OTE0NTAvMjk2Mzg4MDk3LWFlMWM0OGFiLTVmNGMtNDQ1MC04ZjJjLWIyYmU3NzM0MWZhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQyMzAzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTU1YWE0YWIzZGQ3NWI1YzliODBiMWNiMGJlZGM2NjUwZjAwZjFhZDNmYTU4YTU3ZmU3MmFiYTJhNWY3ZDMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Jeb7cIAbhHOD3tVRopbxMUsAHnP0fv-3adwRlFunXg)

But it still don't show which arm has matched - only the overall result of the case... which is not really satisfying :(
