### ISSUE TITLE
edge case: compile callback module attribute ordering

### ISSUE THREAD

**Issue by frankdugan3** [adobe/elixir-styler#120]
## Versions

* Elixir: `Elixir 1.16.0 (compiled with Erlang/OTP 26)`
* Styler: `locked at 0.11.5 (styler) ed924524`

## Example Input

```elixir
defmacro __using__(opts \\ []) do
  quote do
    import Phoenix.LiveView
    @behaviour Phoenix.LiveComponent
    @before_compile Phoenix.LiveView.Renderer

    # Phoenix.Component must come last so its @before_compile runs last
    use Phoenix.Component, Keyword.take(unquote(opts), [:global_prefixes])

    @doc false
    def __live__, do: %{kind: :component, layout: false}
  end
end
```

## Stacktrace / Current Behaviour

```elixir
defmacro __using__(opts \\ []) do
  quote do
    @behaviour Phoenix.LiveComponent

    # Phoenix.Component must come last so its @before_compile runs last
    use Phoenix.Component, Keyword.take(unquote(opts), [:global_prefixes])

    import Phoenix.LiveView

    @before_compile Phoenix.LiveView.Renderer # <-- Problem line

    @doc false
    def __live__, do: %{kind: :component, layout: false}
  end
end
```

It's important to be able to place the [compile callback module attributes](https://hexdocs.pm/elixir/1.15/Module.html#module-compile-callbacks) in very specific places. Is there a workaround for this, or does there need to be a special case to handle `@before_compile`, `@after_compile` and `@after_verify`?

**Comment by novaugust** [comment]
hmm, important indeed! there's no workaround right now.
would lumping those 3 special attributes in with the `use` statements vis-a-vis ordering/grouping be enough? that is, maintain their ordering relative to the `use` statements in the module (we already maintain `use` ordering for this same reason) i think that'd fix your scenario at least

**Comment by novaugust** [comment]
oh hey hey, now that i've said that, here's an ugly workaround for now
```
defmodule BeforeCompileHack do
  defmacro __using__(_) do
    quote do
      @before_compile Phoenix.LiveView.Renderer
    end
  end
end
```
then in your problem area, replace the "@before_compile" with `use BeforeCompileHack`

**Comment by novaugust** [comment]
annnnnd with a quick look at the code, this looked trivial to implement. let me know if the branch at #121 works for you? you can update your mix.exs deps to

```ex
{:styler, github: "adobe/elixir-styler", branch: "me/group-callbacks-with-uses"},
```

to try it out

**Comment by frankdugan3** [comment]
Thanks for the quick response! I thought of that ugly workaround a few hours later after I posted too, lol.

So, running that branch seems to solve the ordering for the callbacks:

![2024-01-19T09:26:08,995818207-06:00](https://github.com/adobe/elixir-styler/assets/10977914/cd9033cc-0f9f-4841-b732-0421c0363510)

But, I have some more complex ones and I discovered that the ordering of `Module.register_attribute` and friends is also a problem, because the compile callbacks reference them as well:

![2024-01-19T09:28:16,900161574-06:00](https://github.com/adobe/elixir-styler/assets/10977914/02f7534c-9cd0-4ebe-86b7-5eba76be3c0f)
![2024-01-19T09:28:51,987034656-06:00](https://github.com/adobe/elixir-styler/assets/10977914/3c38bdac-aa38-40b9-a4e1-f2c5b983efcb)

I might end up needing to fall back to the workaround, that's a lot of edge cases, lol.

**Comment by novaugust** [comment]
yowza, that is indeed a lot of hacking around in modules - is this a typical liveview thing or are you uh, having fun with it as it were? (never liveviewed myself ^.^)

and yeah, not sure what can be done with the `Module.*_attribute` stuff. ultimately styler just starts to break down as a useful tool when you're going deep on metaprogramming. your best bet might be to fork it and disable the moduledefs bit.
if you comment out [just this function head](https://github.com/adobe/elixir-styler/blob/ab8e175f290266e4cfc0985b3e54481b19fff354/lib/style/module_directives.ex#L110-L119) you'll still get the arrangement of directives within a `defmodule`'s immediate body but it'll stop touching the directives inside of any other scope

**Comment by frankdugan3** [comment]
So what I'm working on is basically extending LiveView with a few extra fancy attribute types, so this is definitely not standard stuff. :grin: 

Thanks for the tip, that is interesting. TBH, I only have a small handful of files that go this deep, so I'll probably end up sticking to upstream and just using the workaround. I love the auto formatting and not having to worry about maintenance for the more standard usage!

But, I think the compile callback change is good to keep in, it handles a lot of cases.

**Comment by novaugust** [comment]
> But, I think the compile callback change is good to keep in, it handles a lot of cases.

Cool, I'll merge that bit in at least then.

If I ever get around to designing a way to config styler, disabling that fn head will be at the top of the list =)

**Comment by novaugust** [comment]
thanks for all the feedback ❤️ will ship 0.11.6 later this afternoon

**Comment by frankdugan3** [comment]
Sounds great! Just one thought on the possibility of config in the future: It would be better to disable features per-file with a comment or in config, rather than globally. Formatting directives in the module head is a huge perk for readability, so I wouldn't want to give it up globally!

**Comment by novaugust** [comment]
0.11.6 released to the wild 🤙
