### ISSUE TITLE
Styler move module attribute used in `use` below the first usage

### ISSUE THREAD

**Issue by dkuku** [adobe/elixir-styler#124]
## Versions

* Elixir: use `elixir --version`
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.15.7 (compiled with Erlang/OTP 26)

* Styler: use `mix deps | grep locked | grep styler`
locked at 0.11.6 (styler) 0b0b9936

Styler move a module attribute below the first usage causing an error
## Example Input

```elixir
    @consumer_group "channels". # defined here
    
    use Kafkaesque.ConsumerSupervisor,
      consumer_group_identifier: @consumer_group, # used here
      topics: ["channels.commands"],
      message_handler: ChannelsCommands.Commands.MessageHandler

    def healthcheck, do: Heartbeats.Helpers.kafka_consumer_check(@consumer_group)
```

## Stacktrace / Current Behaviour

```elixir   
    use Kafkaesque.ConsumerSupervisor,
      consumer_group_identifier: @consumer_group,
      topics: ["rchannels.commands"],
      message_handler: ChannelsCommands.Commands.MessageHandler
      
      @consumer_group "channels" #styler moves it here

    def healthcheck, do: Heartbeats.Helpers.kafka_consumer_check(@consumer_group)
```

**Comment by dkuku** [comment]
I see now that this is similar to #65

**Comment by novaugust** [comment]
hey @dkuku, this is covered in the readme [here](https://github.com/adobe/elixir-styler?tab=readme-ov-file#troubleshooting-compilation-broke-due-to-module-directive-rearrangement). sorry for the inconvenience
