### ISSUE TITLE
Elixir 1.15 need double formatting

### ISSUE THREAD

**Issue by epinault** [adobe/elixir-styler#131]
## Versions

* Elixir: use `elixir --version`: 1.15.7
* Styler: use `mix deps | grep locked | grep styler`: 0.11.5

## Example Input
I ran mix format after setting it up,

the following line was not needed any change in term of code but the formatting was changed
```elixir
  block_non_active_emergency_calling_status:
    get_boolean_env.("SOME_VERYLONG_NAME_ENV_VARRIABLE", false),
```

to the following

```elixir
  block_non_active_emergency_calling_status: get_boolean_env.("BLOCK_NON_ACTIVE_EMERGENCY_CALLING_STATUS", false),
```

but then the formatter complains the file is not formatted when in mix format --check-formatted

Running format again fixed it . Though no code was altered by Styler on the 2nd run (as in the code was already altered in first pass)

**Comment by epinault** [comment]
might be something I am doing funky looking at it... if I don t use the plugin after I reformatted my code, then the formatter need to run again. so some slight difference in 1.15 using with and iwthout styler

**Comment by novaugust** [comment]
hey @epinault, thanks for the issue. 
styler doesn't add newlines to anything but module directives, so indeed seems like formatter is doing something for you. part of styler's testing is that [once its formatting is run, nothing changes again](https://github.com/adobe/elixir-styler/blob/6fbaa8ef1eb5aae3581bbb74155bca7f0f31daf3/test/support/style_case.ex#L92-L107) -- so if you do find a repro we can test it with `assert_style` easily =)
but for now i'll close this on the assumption that this isn't a styler problem. but please post again if it ends up being styler misbehaving after all!

**Comment by epinault** [comment]
so what I am seeing is a problem and not sure what s up but line for normal formatter without styler use to respect max length.. 

now it does not with Styler on

```
[R] ↘ xxx_test.exs:54:121 Line is too long (max is 120, was 122).
[R] ↘xxx_test:87:121 Line is too long (max is 1[20](https://gitlab.podium.com/engineering/account-structure/arth0/-/jobs/5676342#L20), was 122).
```

what use to be 

```
  {Tesla.Adapter.Finch, :call,
             [[pool_timeout: 5_000, receive_timeout: 15_000, name: :arth0_deprovision_pool]]},
```

became
```
    {Tesla.Adapter.Finch, :call, [[pool_timeout: 5_000, receive_timeout: 15_000, name: :arth0_deprovision_pool]]},
```

and is not beyond the max line lenght

**Comment by novaugust** [comment]
ahhh, that sounds like you might not have a default line length set in your formatter.exs, in which case styler's using a different default than formatter. setting that value should take care of the switch around

**Comment by epinault** [comment]
I see. I ll try that and let you know!
