### ISSUE TITLE
[Feature Request] Style doc examples

### ISSUE THREAD

**Issue by peake100** [adobe/elixir-styler#14]
I would love for `styler` to style doc examples: So an example without a no-paren function call:

```elixir
@doc """
##Examples
  
​```elixir
iex> some_func 1, 3
4
​```
"""
def some_func(a, b), do: a + b
```

... gets styled as this:

```elixir
@doc """
##Examples

​```elixir
iex> some_func(1, 3)
4
​```
"""
def some_func(a, b), do: a + b
```

For health reasons, I can't volunteer right now, but if this is still open when I'm more recovered, I would love to take this on.

**Comment by novaugust** [comment]
🤔 this is an intriguing one

i'd start off trying to just have code that parses these out and formats them correctly, no styler involved. if you can get it that far it'd be trivial to then add styler into the mix

**Comment by novaugust** [comment]
billy imma close this one for now - i think the way to go about it is to first make a formatter plugin that parses out doc examples, then have _it_ use styler on those snippets. so, it's another tool above-and-beyond styler ;)
