### ISSUE TITLE
`Timex.now(tz)` -> `DateTime.now!(tz)` can result in runtime errors due to Timex tolerating nonstandard timezones

### ISSUE THREAD

**Issue by ivymarkwell** [adobe/elixir-styler#145]
Related issue: https://github.com/adobe/elixir-styler/issues/66

## Versions

* Elixir: `Elixir 1.15.7 (compiled with Erlang/OTP 26)`
* Styler: `0.11.9`

## Example Input

```elixir
Timex.now("GMT-8")
```

## Stacktrace / Current Behaviour

Running `mix format` will convert this into:

```
DateTime.now!("GMT-8")
```

If you run the conversion it bombs:
```
** (ArgumentError) cannot get current datetime in "GMT-8" time zone, reason: :time_zone_not_found
    (elixir 1.15.7) lib/calendar/datetime.ex:845: DateTime.now!/2
```

I would think that this either doesn't get converted or changes it into the literal ask like this:
```elixir
DateTime.add(DateTime.utc_now(), -8, :hour)
```

**Comment by novaugust** [comment]
dang, didn't know that `Timex.now/1` accepted arguments that `DateTime.now!/1` doesn't.
thanks ivy, will probably just turn this rewrite off entirely then 🤔

**Comment by novaugust** [comment]
ps: if you use `"Etc/GMT-8"` i believe you'll get what you want from DateTime. Timex is just letting the tz be loosey-goosey and probably adds the `"Etc/` for you

**Comment by ivymarkwell** [comment]
Oh nice. Good to know thank you.

**Comment by novaugust** [comment]
this'll be fixed in the next release of styler, though that may be a little ways off. thanks again ivy!
