### ISSUE TITLE
[Bug] Invalid code produced when piping operator statement with parentheses into function

### ISSUE THREAD

**Issue by peake100** [adobe/elixir-styler#15]
## Elixir / OTP Version

use `elixir --version`

## Current Behaviour

While debugging some code I wrote the following:

```elixir
(call(a, b) == 1) |> dbg()
```

`styler` output the following, invalid code:

```elixir
call(a, b) |> ==(1) |> dbg()
```

## Expected Behaviour

I would expect the output to remain unchanged, or resolve to this:

```elixir
dbg(call(a, b) == 1)
```

**Comment by novaugust** [comment]
just a little mistake where `==` wasn't included in the list of valid pipe start operators. 
thanks billy!
(i found another bug while debugging this one by chance, so double win :D)
