### ISSUE TITLE
Empty line gets removed when formatting pipe to simple function call

### ISSUE THREAD

**Issue by janpieper** [adobe/elixir-styler#162]
## Versions

```console
$ elixir --version
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.16.2 (compiled with Erlang/OTP 26)
```

```console
$ mix deps | grep locked | grep styler
  locked at 0.11.9 (styler) 8b7806ba
```

## Example Input

```elixir
foo
|> bar()

run()
```

### Expected

```elixir
bar(foo)

run()
```

### Current

```elixir
bar(foo)
run()
```

**Comment by novaugust** [comment]
hey jan, thanks for the issue (especially the super simple repro ❤️ )

i could go either way on this, but given that the formatter always _adds_ a newline to multiline statements, it doesn't seem incorrect to me that styler _removes_ that newlineline when collapsing the same. 

so i'll probably leave this as more of a feature than a bug.

**Comment by GregMefford** [comment]
I can definitely see it both ways in the case where it's re-styling the input you described.

However, I think that if Styler saw the following in existing code:

```elixir
bar(foo)

run()
```

I would _not_ expect it to arbitrarily remove that newline, and therefore I feel like the way it currently works is probably correct / consistent.
