### ISSUE TITLE
Need configurability

### ISSUE THREAD

**Issue by evansorenson** [adobe/elixir-styler#172]
Hi, 

I work at a company with a very large Elixir repo and it isn't feasible to A) apply all styles at once or B) to apply to all files at once. Therefore, I would like to make the styles configurable (turning on/off) and potentially a file whitelist/blacklist (passed on paths).

It seems in the past you have been against adding configurability. Are you open to reconsidering your stance? I believe configurability would make the library much easier to adopt.

**Comment by evansorenson** [comment]
Also, just wanted to say this library is fantastic :) I use it for all my side projects

**Comment by novaugust** [comment]
Cheers Evan =) appreciate the kind words. i feel your pain on shipping to a large project, as i experienced that when i created styler! (or when i'm trying out scary new things like the mix config sorting in the 1.0 releases)

adding configuration for on/off isn't feasible for me from a maintainability viewpoint - i go into it [here](https://github.com/adobe/elixir-styler/pull/127#issuecomment-1912242143). as saveman says in that PR, there's [lots of forks out there](https://github.com/adobe/elixir-styler/forks) where folks have set up some sort of on/off configuration. in fact, that's what almost all the forks are for as far as i've seen :) you could easily copy what they're doing if you only want some style rewrites.

but! as i was saying, i've experienced what you're talking about on our internal project, so here's how i get new (potentially dangerous) styler features in on an existing codebase where you're unable to just do it all in one fell swoop 

the idea is, piecemeal modify file-by-file, or group-of-files at a time, for ease of review. to accomplish that:

1. add styler to your mix.exs as normal
2. likewise, add it to your plugins
3. format only the files you want to ship in a single reviewable PR: `mix format lib/file1.ex lib/file2.ex lib/all_files_in_this_folder`
4. commit only those files and ship it
5. rinse and repeat

you could also commit the changes to mix.exs and .formatter.exs, and just comment out the `plugins: [Styler]` line until you're ready to turn it on for good

now all that said, if you're on 1.0.0-rc.0, the only potential shippable-breakage styler will introduce is in config sorting, and that only if your config had a hidden duplicate configuration. there's also [this one about alias lifting](https://github.com/adobe/elixir-styler/issues/141) but the compiler will tell you if that happens, so no stress on reviewers.
