### ISSUE TITLE
`with true <- foo do` -> `if foo do`

### ISSUE THREAD

**Issue by novaugust** [adobe/elixir-styler#173]
```elixir
# before
with true <- foo do
  bar
end

# after
if foo do
  bar
end
 ```

if someone's short-circuiting via `||` to return an else, use else
```elixir
# before
with true <- foo || {:error, :shouldve_used_an_if_statement} do
  bar
end

# after
if foo do
  bar
else
  {:error, :shouldve_used_an_if_statement}
end
```

**Comment by s3cur3** [comment]
Hi there! 👋 Friendly heads up from the Quokka project, which forked off Styler in early 2025:

This rewrite is not semantically equivalent! `with true <- foo, do: bar` returns `foo` when it `foo` doesn't match, but `if foo, do: bar` returns nil.

**Comment by novaugust** [comment]
thanks @s3cur3 - the readme notes that styler knowingly does semantically unequivalent rewrites [here](https://github.com/adobe/elixir-styler#warning-styler-can-change-the-behaviour-of-your-program)

**Comment by s3cur3** [comment]
Fair enough! 👍

**Comment by novaugust** [comment]
seems like quokka, as a fork, has a similar warning on its readme eh https://github.com/emkguts/quokka#warning--warning
