### ISSUE TITLE
when de-piping an assignment, try to fit it on one line

### ISSUE THREAD

**Issue by novaugust** [adobe/elixir-styler#181]
## Example Input

```elixir
# given      
x =
  y
  |> Enum.map(&f/1)
  |> Enum.join()

# we get
x =
  Enum.map_join(y, &f/1)

# we want
x = Enum.map_join(y, &f/1)
```

**Comment by janpieper** [comment]
Even without de-piping, I would be happy to see styler format it into one line.

```elixir
x = 
  Enum.map_join(y, &f/1)
```

should become

```elixir
x = Enum.map_join(y, &f/1)
```

**Comment by novaugust** [comment]
amen to that. always wished the formatter would move things up if you increased line length in a codebase, or updated a line to be less long (hence styler!)
i'll spike on that when i work on this issue and see if it can't happen together, thanks for the suggestion
