### ISSUE TITLE
Invalid formatting of `!` when restructuring a pipe

### ISSUE THREAD

**Issue by nherzing** [adobe/elixir-styler#183]
## Versions

* Elixir: Elixir 1.17.0 (compiled with Erlang/OTP 26)
* Styler: locked at 1.0.0-rc.2 (styler) 35f8f0ec

## Example Input

```elixir
!is_number(42) |> IO.puts()
```

## Stacktrace / Current Behaviour
This code is formatted as
```elixir
42 |> is_number() |> !() |> IO.puts()
```
which is not going to evaluate. Attempting to run this formatted code results in
```
** (ArgumentError) cannot pipe 42 |> is_number() into !nil, the :! operator can only take one argument
    (elixir 1.17.0) lib/macro.ex:318: Macro.pipe/3
    (stdlib 5.2) lists.erl:1594: :lists.foldl/3
    (elixir 1.17.0) expanding macro: Kernel.|>/2
    iex:1: (file)
    (elixir 1.17.0) expanding macro: Kernel.|>/2
    iex:1: (file)
```

**Comment by novaugust** [comment]
thanks for the issue & repro! i'll make sure styler knows to add a `Kernel.` in front of that `!`. not the prettiest solution, but sometimes things look sad when there are strict rules :/
