### ISSUE TITLE
The `mix format` process being hung up while one of the `if` statements body is empty 

### ISSUE THREAD

**Issue by itamm15** [adobe/elixir-styler#196]
## Versions

* Elixir: 1.17
* Styler:1.0.0

## Example Input

```elixir
defmodule StylerError.ErrorCase do
  def test do
    a = 1
    b = 2

    if a != b do
      # TODO: handle this case
    else
      :ok
    end
  end
end
```

## Stacktrace / Current Behaviour

Without having the Styler passed in the `.formatter.exs` file (see https://github.com/itamm15/elixir-styler-error-repo/commit/bb3b83c8858f7232fa916e2b771b67c9523c2849);

![image](https://github.com/user-attachments/assets/f26f755f-49de-49e1-97db-13548b2b03d9)

With Styler passed in the `.formatter.exs` file (see https://github.com/itamm15/elixir-styler-error-repo/commit/d37a4eba8569f01de4292fde68ea91ade5b29771); 

![image](https://github.com/user-attachments/assets/9b8a0e09-d5df-4a67-afcb-300d89d2386f)

(I waited for about 10 minutes, but nothing happened)

But when I explicitly set the `nil` in the first statement body; 

![image](https://github.com/user-attachments/assets/b8449fc2-e069-44fe-a522-dc172e7505b2)

It works! (Styler just removed that case, and moved the comment to the `else` body), previously with `nil` before Styler change;

```elixir
    if a != b do
      # TODO: handle this case
      nil
    else
      :ok
    end
```

I created a repo for that https://github.com/itamm15/elixir-styler-error-repo, and there is an example test file https://github.com/itamm15/elixir-styler-error-repo/blob/master/lib/styler_error/error_case.ex

(Thanks for that lib, and hopefully I haven't missed anything in the docs, that this is an expected scenario 😄)

**Comment by novaugust** [comment]
thanks for the report @itamm15, have it fixed on main / will be out in 1.1 =)
