### ISSUE TITLE
un-piping causes CompileError in 1.2.0

### ISSUE THREAD

**Issue by paulswartz** [adobe/elixir-styler#204]
## Versions

Erlang/OTP 27 [erts-15.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

locked at 1.2.0 (styler) 7a8b5e82

## Example Input

```elixir
value
|> Module.function(value2 |> Module.internal_function() |> Module.internal_function2())
|> Module.function2()
```

re-written to:

```elixir
value
|> (value2
    |> Module.internal_function()
    |> Module.internal_function2()
    |> Module.function())
|> Module.function2()
```

with a compile error:
```
error: undefined function value2/1
```

## Stacktrace / Current Behaviour

Looks like this re-write causes a CompileError: https://github.com/mbta/ride_along/pull/65/files#diff-8e8265b0572eec29f100e902bc4e4dba522b46e8c7d855beaba8c864c4ca7126L75-L82

I'm guessing this was introduced by #133.

**Comment by novaugust** [comment]
tyty! will have it fixed in a jiffy
