### ISSUE TITLE
How to configure the formatter to not sort configuration files

### ISSUE THREAD

**Issue by JasterV** [adobe/elixir-styler#206]
I use styler for one of my projects and so far I love it, it is super helpful.

Recently I found out that it was messing with my configuration files and I was wondering if there is a way to prevent styler from doing that.

By messing I mean the default behavior, which is sorting the configuration alphabetically.
I don't want to do that because I want to sort myself my own configuration files by features/services/theme.
Also I like to add comments on configuration files to explain what certain configurations are for, but styler just messes with it and moves the comments somewhere else.

Is there a way to configure that from the `.formatter.exs` file?

**Comment by novaugust** [comment]
from comments on this thread, you can disable styler in your config directory by adding a .formatter.exs file within that directory
https://github.com/adobe/elixir-styler/issues/187#issuecomment-2452281229
