### ISSUE TITLE
Produces compiler errors for Ecto queries using "in" macro

### ISSUE THREAD

**Issue by Nezteb** [adobe/elixir-styler#24]
## Elixir / OTP Version
```
❯ cat .tool-versions 
elixir 1.14.1-otp-25
erlang 25.1.1
```

## Current Behaviour

For several of my work projects, we do `require Ecto.Query` (instead of `import Ecto.Query, only: ...`) and then call `Ecto.Query.from(...)`. Inside of [the `from` macro](https://github.com/elixir-ecto/ecto/blob/v3.10.1/lib/ecto/query.ex#L939), an unqualified `in` is valid. However, `elixir-styler` makes the following change:

<img width="1137" alt="Screenshot 2023-05-04 at 8 22 32 AM" src="https://user-images.githubusercontent.com/3588798/236254197-8f819b66-b088-44fb-a180-d8ed3b636e2b.png">

<img width="1165" alt="Screenshot 2023-05-04 at 8 10 36 AM" src="https://user-images.githubusercontent.com/3588798/236251322-8bae6844-4450-4e90-959d-d63b304d2bda.png">

Which causes a compilation error:
```
syntax error before: in. "in" is a reserved word in Elixir and therefore its usage is limited. For instance, it can't be used as a variable or be defined nor invoked as a regular function
```

A fix in this case is to change `in` to `Ecto.Query.in`.

## Expected Behaviour

I'm not sure how to avoid this, unless `elixir-styler` is able to detect which functions are macros and skip them or automatically fully qualify them?

**Comment by Nezteb** [comment]
Actually, `Ecto.Query.in` doesn't solve everything:
<img width="1144" alt="Screenshot 2023-05-04 at 8 34 03 AM" src="https://user-images.githubusercontent.com/3588798/236257036-f2fe53f4-f4df-418e-ae9e-d2c44f07d8b4.png">
```
** (Ecto.Query.CompileError) unbound variable `po` in query. If you are attempting to interpolate a value, use ^var
```

**Comment by novaugust** [comment]
thanks @Nezteb , i'll have a fix for this shortly :)
(can't believe the codebases i work with always just import, never require o.O)

**Comment by novaugust** [comment]
v0.5.2 will fix your problems =) thank you for the issue!

**Comment by Nezteb** [comment]
For future reference (in case anyone stumbles upon this in the future), in some cases this still breaks:
<img width="1127" alt="Screenshot 2023-05-04 at 9 44 38 AM" src="https://user-images.githubusercontent.com/3588798/236271270-693788f1-b781-4f3a-bed1-a9a027babb27.png">

```
** (Ecto.Query.CompileError) unbound variable `c` in query. If you are attempting to interpolate a value, use ^var
```

The solution is that instead of:
```elixir
(c in MySchema)
|> Ecto.Query.from(where c.thing ...)
```
You should use:
```elixir
Ecto.Query.from(c in MySchema, where c.thing ...)
```

**Comment by Nezteb** [comment]
> i'd normally write that using the keyword DSL

Yeahhh I normally would too, but this is a large codebase I only started working with earlier this year. 😅
