### ISSUE TITLE
Pinned variables in matches are formatted incorrectly

### ISSUE THREAD

**Issue by Nezteb** [adobe/elixir-styler#27]
## Elixir / OTP Version
```
❯ cat .tool-versions 
elixir 1.14.1-otp-25
erlang 25.1.1
```

Using `elixir-styler` version 0.5.2.

## Current Behaviour

Example 1:
<img width="1167" alt="Screenshot 2023-05-04 at 10 34 29 AM" src="https://user-images.githubusercontent.com/3588798/236285744-e67db4c5-708d-455e-831e-656cc7d9e29f.png">

Which gives:
```
** (ArgumentError) cannot pipe some_var_ids into ^nil, the :^ operator can only take one argument
```

If I revert and rerun `mix format`, there is a different result that is still weird:
<img width="1162" alt="Screenshot 2023-05-04 at 10 35 05 AM" src="https://user-images.githubusercontent.com/3588798/236285900-f1a5692e-37aa-4573-9e0d-cd00422ffc5b.png">

Example 2:
<img width="1140" alt="Screenshot 2023-05-04 at 10 32 09 AM" src="https://user-images.githubusercontent.com/3588798/236285594-589e4695-8407-4864-8225-89ca5246792a.png">

Oddly enough, if I revert the file and then rerun `mix format`, this same code is untouched. 🤔 

I'm guessing that the non-deterministic behavior is not intended either, though that's probably a separate issue? 😅 

## Expected Behaviour
Unsure what should actually happen here, but perhaps pinned variables should be ignored?

**Comment by novaugust** [comment]
just when you think you've seen all the ways people write ecto queries 😂 

>Unsure what should actually happen here, but perhaps pinned variables should be ignored?

yeah, i'll add pin as a valid start as well

**Comment by Nezteb** [comment]
> just when you think you've seen all the ways people write ecto queries 😂

Yeah I find stuff like this relatively often. 😅

**Comment by novaugust** [comment]
if it makes your life easier, all i ever need is the snippet that does weird things for you, to save you the work of blacking out screenshots. can just write 
"Heyyyy this snippet breaks things"
```elixir
^foo
|> Ecto.Query.blah(...)
```

**Comment by novaugust** [comment]
want to just point at latest main here on GH until you stop finding issues? i can cut a release after that ^.^

**Comment by Nezteb** [comment]
Alright, I've tested `main` on three large work-related Elixir services, and everything is good so far!

There were a few times where a format would cause code to not compile or tests to fail, but each of those cases were actually good opportunities for refactoring that I was able to fix!

I look forward to trying this as more of the items from https://github.com/adobe/elixir-styler/issues/18 are added. 😄

**Comment by novaugust** [comment]
>There were a few times where a format would cause code to not compile or tests to fail, but each of those cases were actually good opportunities for refactoring that I was able to fix!

The only thing I'm aware of breaking compilation is when there are `alias` before other directives that are then used in them. did you see anything apart from that? (i'll be updating the readme to let people know what to expect on a first run)

**Comment by Nezteb** [comment]
> when there are `alias` before other directives that are then used in them. did you see anything apart from that?

Nope! Just stuff like:

```elixir
alias Some.Long.Path
use Path.Thing
```

And even worse: (this was technically only a compiler warning, but still)
```elixir
@some_module_attribute :thing
use Some.Weird.Macro # depends on @some_module_attribute being defined
```

So now I've changed those to:

```elixir
use Some.Long.Path.Thing

alias Some.Long.Path
```

And:
```elixir
# using actual __using__ opts instead of module attributes
use Some.Weird.Macro,
  some_module_attribute: :thing
```

😄

**Comment by novaugust** [comment]
yep, that's 100% the problems i see on first run as well. thanks!
