### ISSUE TITLE
unquote piped into unquote results in invalid `unquote/2` invocation

### ISSUE THREAD

**Issue by elliottneilclark** [adobe/elixir-styler#51]
## Versions

* Elixir: Elixir 1.14.5 (compiled with Erlang/OTP 25)
* Styler:   locked at 0.7.12 (styler) 9b309b7c

## Example Input

```elixir
  defp pipe(left, right) do
    quote do
      unquote(left) |> unquote(right)
    end
  end
```

## Stacktrace / Current Behaviour

That produces:

```elixir
  defp pipe(left, right) do
    quote do
      unquote(unquote(left), right)
    end
  end
```

**Comment by novaugust** [comment]
Heya, thanks for the issue.

This doesn't look like something we'll fix in Styler. Sometimes when it makes kaboomy code, it's a good chance to zoom out and see if things can just be written different -- kind of like when the formatter makes code look weird. 

In this case, I'd suggest using `bind_quoted` to remove the use of `unquote`. At that point, Styler would rewrite `left |> right` as just `right(left)`, and your code will be just that little bit happier.

**Comment by elliottneilclark** [comment]
> In this case, I'd suggest using bind_quoted to remove the use of unquote. 

That's not possible in the place that I extracted the code from, but I understand your point of there are other ways to write this. (this is from code generation path that produces code from a `Macro.to_string` and the final format is more important so it's unsual) I still think this is worth solving by ignoring code in `quote`.

From experience with black/clang-format on large code bases I can tell you that you need to either focus on never producing broken code, or allow configuring styler in specific cases. `#noqa` or the like.  The project README shows this already becoming apparent. There are a number of gotchas around styler making incorrect changes. You can't turn those checks off like you can with credo, and you have to manually fix them.

**Comment by novaugust** [comment]
thanks for the input elliott, but having styler style code inside of quote is quite intentional - we like to keep all our code consistent. that said, we're very supportive of people forking the library and making the tool their own.

**Comment by novaugust** [comment]
while we don't want to disable styler in quotes, making it work with the idea that some `unquote` usages only work with a preceding pipe is good style, if you will. got it fixed on main, thanks

**Comment by elliottneilclark** [comment]
> having styler style code inside of quote is quite intentional 

Totally, that was simply the easiest tactical fix I could see, since creating quoted piped code wasn't that common. Thanks for the even better solution!
