### ISSUE TITLE
[Feture Request] Configuration to disable individual Styler rules

### ISSUE THREAD

**Issue by gerbal** [adobe/elixir-styler#56]
We're using styler on a large code base, and like all of the default rules except for adding `@moduledoc false` to all modules by default. Our team's convention is that disabling moduledoc should be a conscious choice by the developer, and not a default rule. 

An ideal outcome would be to provide a configuration file like `.styler.exs` where we can disable or enable (or even customize) individual rules by referencing the corresponding Credo check or a Styler specific rule module.

Something like

```elixir
# .styler.exs
%{
  config: %{
    rules: %{
      enabled: [
        Credo.Check.Consistency.MultiAliasImportRequireUse,
        Credo.Check.Consistency.ParameterPatternMatching,
        Credo.Check.Readability.AliasOrder,
        Credo.Check.Readability.BlockPipe,
        Credo.Check.Readability.LargeNumbers,
        # Credo.Check.Readability.ModuleDoc,
        Credo.Check.Readability.MultiAlias,
        Credo.Check.Readability.OneArityFunctionInPipe,
        Credo.Check.Readability.ParenthesesOnZeroArityDefs,
        Credo.Check.Readability.PipeIntoAnonymousFunctions,
        Credo.Check.Readability.PreferImplicitTry,
        Credo.Check.Readability.SinglePipe,
        Credo.Check.Readability.StrictModuleLayout,
        Credo.Check.Readability.UnnecessaryAliasExpansion,
        Credo.Check.Refactor.CaseTrivialMatches,
        Credo.Check.Refactor.FilterCount,
        Credo.Check.Refactor.MapInto,
        Credo.Check.Refactor.MapJoin,
        Credo.Check.Refactor.PipeChainStart
      ]
    }
  }
}
```

**Comment by novaugust** [comment]
Hey gerbal, styler harkens more to the configuration style of formatter than it does to credo's. there's currently no intention to make its "styles" on/off configurable, as that defeats the purpose of a consistent codebase.
thanks for checking the project out, hope it's still useful to you regardless! ❤️

**Comment by novaugust** [comment]
Gerbal, I understand my response wasn't what you were looking for, but responding with a 👎 isn't an appropriate way to engage here, nor is it suited to our [Code of Conduct](https://github.com/adobe/.github/blob/main/CODE_OF_CONDUCT.md). Keep in mind that maintaining open source repos like this is an act of free labor from the authors =)

That said, here's our [README's section on Configuration](https://github.com/adobe/elixir-styler#configuration) 

> ### Configuration
> There isn't any! This is intentional.
>
> Styler's @adobe's internal Style Guide Enforcer - allowing exceptions to the styles goes against that ethos. **Happily, it's open source and thus yours to do with as you will =)** \[_emphasis added_]

So if you'd like to maintain a fork, you can find the offending moduledoc code in the `module_directives.ex` file. Hope that helps!
