### ISSUE TITLE
Keyword list as sole argument in a pipe in a map: syntax error after formatting

### ISSUE THREAD

**Issue by mxgrn** [adobe/elixir-styler#60]
## Versions

* Elixir: 1.15.0
* Styler: 0.8.1

## Example Input

```elixir
    %{
      a: Foo.bar(baz: true) |> Quux.quux()
    }
```

## Current output

```elixir
    %{
      a: baz: true |> Foo.bar() |> Quux.quux()
    }
```

## Expected output

```elixir
    %{
      a: [baz: true] |> Foo.bar() |> Quux.quux()
    }
```

**Comment by novaugust** [comment]
thanks for the issue! should be solved in the next release.
funny that it only happens depending on the parent node - `Foo.bar(baz: true) |> Quux.quux()` by itself worked just fine :)

**Comment by novaugust** [comment]
0.8.2 is out, sorry for spacing to ship until now =)
