### ISSUE TITLE
block manipulation is cruel to comments

### ISSUE THREAD

**Issue by novaugust** [adobe/elixir-styler#79]
the `if/unless/with` statement manipulation was all implemented under the SingleNode module, which ignores comments (.. because it's suppose to only manipulate single nodes). given that if and unless both swap blocks around without updating lines/comments, comments will end up in the wrong places

here's a tdd:

```ex
    test "moves comments" do
      assert_style(
        """
        if not :ok do
          # do
          do_body
        else
          # else
          else_body
        end
        """,
        """
        if :ok do
          # else
          else_body
        else
          # do
          do_body
        end
        """
      )
    end
```
fails with

```
  1) test if/else moves comments (Styler.Style.SingleNodeTest)
     test/style/single_node_test.exs:671
     Assertion with == failed
     code:  assert styled == expected
     left:  "if :ok do\n  # do\n  # else\n  else_body\nelse\n  do_body\nend"
     right: "if :ok do\n  # else\n  else_body\nelse\n  # do\n  do_body\nend"
     stacktrace:
       test/style/single_node_test.exs:672: (test)
```

a fix would move this multi-node manipulation to its own style (`Blocks`?) and update the line meta of all nodes in the do/else blocks, and likewise move comments within those ranges to their new homes. examples of manipulating line numbers and comment line numbers can be found in the `Defs` style

**Comment by sabiwara** [comment]
I found another example, seems related but let me know if it should be reported separately.
In this case, comments are jumping functions.

```elixir
  def foo(x) do
    case x > 2 do
      true -> :ok
      false -> :error
    end
  end

  # BAR COMMENT 1
  def bar(x) do
    # BAR COMMENT 2
    x +  1
  end
```

becomes

```elixir
  def foo(x) do
    if x > 2 do
      :ok

      # BAR COMMENT 1
      # BAR COMMENT 2
    else
      :error
    end
  end

  def bar(x) do
    x + 1
  end
```

**Comment by novaugust** [comment]
thanks sabiwara. similar situation, but a different problem area -- that's due to the `if` ast generated by [styled_if/3](https://github.com/adobe/elixir-styler/blob/main/lib/style/single_node.ex#L255-L261) not grabbing line numbers from the old AST when it creates the new node. there's even a TODO there in my link, shameful ;)

close enough to the same issue that having your example here will be just fine. thanks for reporting!
