### ISSUE TITLE
Columnar alignment

### ISSUE THREAD

**Issue by saleyn** [adobe/elixir-styler#81]
Is it possible to define styling rules, so that the formatter would produce columnar alignment such that
```elixir
def some_fun do
  a = 1
  bc = 2
  ef_gh = 3
 {a, bc, ef_gh}
end
```
would become
```elixir
def some_fun do
  a     = 1
  bc    = 2
  ef_gh = 3
  {a, bc, ef_gh}
end
```

**Comment by novaugust** [comment]
sorry saleyn, afraid not =) styler still relies on formatter behind the scenes, so its rules win out in the end.
