### ISSUE TITLE
Piping wrapped function calls requires formatter to run multiple times for proper output

### ISSUE THREAD

**Issue by tomjschuster** [adobe/elixir-styler#94]
## Versions

* Elixir: 1.15.7
* Styler: 0.10.2

## Example Input

```elixir
    f(g(h(x))) |> j()
```

## Stacktrace / Current Behaviour

`mix format` needs to be called 3 times to get the expected output:
```elixir
x |> h() |> g() |> f() |> j()
```

Here are the results for each `mix format` call:
1. `g(h(x)) |> f() |> j()`
2. `h(x) |> g() |> f() |> j()`
3. `x |> h() |> g() |> f() |> j()`

**Comment by novaugust** [comment]
thanks tom! ❤️
